server:
  port: 9800
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    url: jdbc:h2:mem:xzl_manageSystem
#    driver-class-name: org.h2.Driver
#    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    mode: LEGACYHTML5